global:
  scrape_interval: 15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: 'flight-booking-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['flight-app:8080']
    scrape_interval: 10s
    scrape_timeout: 5s